server:
  port: 8088
  servlet:
    context-path: /

#配置mysql的连接信息（配置数据源）
#注意这里引用了要选的子配置文件
spring:
  profiles:
    active: dev
  ai:
    openai:
      api-key: ${spring.ai.openai.api-key}
      base-url: ${spring.ai.openai.base-url}
      chat:
        options:
          model: ${spring.ai.openai.chat.options.model}
          temperature: ${spring.ai.openai.chat.options.temperature}
  datasource:
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
    driver-class-name: ${spring.datasource.driver-class-name}
    url: ${spring.datasource.url}

  #配置redis的连接信息
  data:
    redis:
      host: ${spring.data.redis.host}
      port: ${spring.data.redis.port}
      password: ${spring.data.redis.password}
      database: ${spring.data.redis.database}

  #让spring支持bean的循环依赖, BeanA 依赖 BeanB，同时BeanB也依赖BeanA，这就是循环依赖
  main:
    allow-circular-references: true

  #后端对象返回json时，指定日期时区和日期格式（否则数据会有时差）
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

#指定mapper.xml文件在什么位置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  #配置mybatis框架执行sql语句时，把sql语句打印到控制台
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#项目启动日志的打印级别
logging:
  level:
    root: info

#定义定时任务的调度时间(秒/分)，当前是5分钟/3分钟

