spring:
  ai:
    openai:
      api-key: sk-xDeOgEhE1DlYtbfEJUKbELwqZciTP7hI4K0sa6T4dGxzCErl
      base-url: https://api.chatanywhere.tech
      chat:
        options:
          model: gpt-3.5-turbo
          temperature: 0.4

  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dlyk

  data:
    redis:
      host: 192.168.205.101
      port: 6379
      password: 123456
      database: 0